apiVersion: apps/v1
kind: Deployment
metadata:
  name: pparsai-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pparsai-app
  template:
    metadata:
      labels:
        app: pparsai-app
    spec:
      containers:
      - name: pparsai-app
        image: piyushparsai/docker-flask:1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000


---

apiVersion: v1
kind: Service
metadata:
  name: pparsai-app
spec:
  type: LoadBalancer
  selector:
    app: pparsai-app
  ports:
  - port: 80
    targetPort: 5000

